// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrZm4mfMAyRkmwPI0BQ7U5Ycaqbygv20A',
    appId: '1:306397029142:web:998d7786e1311caff4e637',
    messagingSenderId: '306397029142',
    projectId: 'smiccat-5d93b',
    authDomain: 'smiccat-5d93b.firebaseapp.com',
    storageBucket: 'smiccat-5d93b.appspot.com',
    measurementId: 'G-6XG0EDYRYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrMVC7dd8DFRlN-VtUlv4P6IuTHSUoPRs',
    appId: '1:306397029142:android:fa6227092dbeb93df4e637',
    messagingSenderId: '306397029142',
    projectId: 'smiccat-5d93b',
    storageBucket: 'smiccat-5d93b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG1eTYtCNZ8XUIeH6g2yJ3oCi-DTpvvcQ',
    appId: '1:306397029142:ios:84f4707645fccb69f4e637',
    messagingSenderId: '306397029142',
    projectId: 'smiccat-5d93b',
    storageBucket: 'smiccat-5d93b.appspot.com',
    iosBundleId: 'com.example.integradora21',
  );
}
