// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxtxg5I04elIpVLyRDDaKTkvQtoT3fJ4M',
    appId: '1:608237155140:web:a60440262325556946dd11',
    messagingSenderId: '608237155140',
    projectId: 'smiccat-f890c',
    authDomain: 'smiccat-f890c.firebaseapp.com',
    storageBucket: 'smiccat-f890c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxa7zC_XQ7v8mL7fxENc-kJwchcqnwB9Y',
    appId: '1:608237155140:android:95251113840d307846dd11',
    messagingSenderId: '608237155140',
    projectId: 'smiccat-f890c',
    storageBucket: 'smiccat-f890c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHd4RgWrhOiTGz173D6bw_KShQRhcpE5k',
    appId: '1:608237155140:ios:016b6456590e78d646dd11',
    messagingSenderId: '608237155140',
    projectId: 'smiccat-f890c',
    storageBucket: 'smiccat-f890c.appspot.com',
    iosBundleId: 'com.example.integradora21',
  );
}
